### ISSUE TITLE
Consider better validation logic

### ISSUE THREAD

**Issue by michimune** [ikeay/cs50#3]
https://github.com/ikeay/cs50/blob/6176a972da2c3dab047aa6af0c078d025a65f510/caesar/caesar.c#L48

I am guessing you'd want to check if any non-digit character is contained in the specified string when atoi() returns a zero. I'd suggest to simply check if (str[i] < '0' || str[i] > '9') instead.

It will return -1 if a negative number is specified, but it should be ok since your code doesn't expect any negative number. Also the previous issue that I raised (#2) will be automatically resolved.

**Comment by ikeay** [comment]
Deeply thanks for reviewing this project. It is exactly right you pointed out. I attempted to check a digit character or not in this code.

I want to fix your indication right now, but this code may be deleted by another pull request. So please let me pend this issue 🙇 

ref. https://github.com/ikeay/cs50/pull/4

**Comment by michimune** [comment]
Sounds good.
